# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/config for details.
runtime: python37
instance_class: F2

handlers:
- url: /favicon\.ico
  static_files: static/img/bread-favicon.ico
  upload: static/img/favicon\.ico
  expiration: 7d
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Last-Modified: "Tue, 21 July 2015 00:00:00 GMT"
    Cache-Control: "max-age=2592000"
- url: /static
  static_dir: static/
  secure: always
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: 'bakerydemo.settings.production'
  GOOGLE_APPLICATION_CREDENTIALS: 'ornate-hangar-125622-e16e04136ba8.json'
  GS_BUCKET_NAME: 'ornate-hangar-125622-static'
  GS_PROJECT_ID: 'ornate-hangar-125622'
  ELASTICSEARCH_ENDPOINT: '10.128.0.2'
  DATABASE_NAME: 'wagtail'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'abcd1234'
  DATABASE_HOST: '/cloudsql/ornate-hangar-125622:us-central1:demo-db-postgres'
  SECRET_KEY: 'dfg$doijovn@opj(lk234#!sdf^dgdfg)24sfGfgD$DFG%dgfg'

vpc_access_connector:
  name: 'projects/ornate-hangar-125622/locations/us-central1/connectors/es-connector'