version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ornate-hangar-125622-e16e04136ba8.json
      DJANGO_SETTINGS_MODULE: bakerydemo.settings.local
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      GS_PROJECT_ID: ornate-hangar-125622
      GS_BUCKET_NAME: ornate-hangar-125622-static
      DATABASE_NAME: app_db
      DATABASE_USER: app_user
      DATABASE_PASSWORD: changeme
      DATABASE_HOST: db
      SECRET_KEY: liundfglsubdiguhstioughsoiuthgiurtnlsjntgilu
      DJANGO_LOG_LEVEL: INFO
    build:
      context: ../../..
      dockerfile: infrastructure/docker/local/Dockerfile
    volumes:
      - media-root:/code/bakerydemo/media
      - ~:/root:delegated
      - /Users:/Users:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config:/root/.config:delegated
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  media-root:
